### PR TITLE
WCON fixes

### PR DESCRIPTION
**Pull request by MichaelCurrie**
Remove old content from WCON that was experimental or transitory.

### CODE REVIEW

**Comment by slarson** [comment]
@MichaelCurrie @JimHokanson @clinzy @cheelee What would be needed to merge this?

**Comment by MichaelCurrie** [comment]
We should fix the Travis checks and then it would be safe to merge.

**Comment by JimHokanson** [comment]
Looked at the checks and getting files from Google Drive is failing. This has been a pain for a while now as Google tries to shutdown Drive access for file serving. Do we have a known workaround? Ideally we could put these test files on a different server.

**Comment by JimHokanson** [comment]
This looks like it is the "current" workaround for this nonsense:
https://gist.github.com/iamtekeste/3cdfd0366ebfd2c0d805

**Comment by JimHokanson** [comment]
Update. I applied the temporary fix for Google Drive. The following are now issues:

See https://travis-ci.org/openworm/open-worm-analysis-toolbox/builds/384995496 for reference.

1. It seems that older versions of Python 3 (3.3 and 3.4) are not compatible with some of the dependencies. Can we just get rid of those versions of Python? 
2. OpenCV is no longer working with Python 3.5 (can't import cv2). We should also look into downloading opencv rather than making it since I think Anaconda is now distributing it and it takes 20 minutes to build from source
3. In one of the tests for Python 2.7 (and probably 3.5 once we get opencv) we have the following error:
```
compute_area_by_rasterization
======================================================================
ERROR: test_areas.test_areas
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/openworm/open-worm-analysis-toolbox/tests/test_areas.py", line 86, in test_areas
    nw_calculated.contour)
  File "/home/travis/build/openworm/open-worm-analysis-toolbox/tests/test_areas.py", line 60, in compute_area_by_rasterization
    im_dum = np.zeros(im_size)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

**Pull request merged**
